spring:
  profiles:
    active: local

  application:
    name: calendar-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nukabyte@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password} #google 보안에 2단계 인증 활성화, 앱 비밀번호 생성해서 변경
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT 설정
jwt:
  secret: myCalendarSecretKeyForJWT2024!@#
  expiration: 86400000 # 24시간

# 이메일 설정

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    duckhu.calendar: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

admin:
  emails: nukabyte@gmail.com
