spring:
  profiles:
    active: local

  application:
    name: calendar-api

  mvc:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 5  # Supabase 무료 플랜이면 5-10 권장
      minimum-idle: 2        # 최소 연결 수 줄이기
      idle-timeout: 300000   # 5분으로 줄이기
      max-lifetime: 900000   # 15분으로 줄이기
      leak-detection-threshold: 60000  # 연결 누수 감지 추가

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          autocommit: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nukabyte@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password} #google 보안에 2단계 인증 활성화, 앱 비밀번호 생성해서 변경
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT 설정
jwt:
  secret: duckhu-calendar-jwt-secret-key-must-be-at-least-32-characters-long-for-security
  expiration: 3600000 # 1시간 (밀리초)

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    duckhu.calendar: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

admin:
  emails: nukabyte@gmail.com

app:
  dev:
    mode: true
