spring:
  profiles:
    active: local

  # Vue.js SPA 라우팅을 위한 설정
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

  application:
    name: calendar-api

  # Spring Boot가 Vue.js 라우팅을 처리하도록 설정
  mvc:
    throw-exception-if-no-handler-found: false
    static-path-pattern: /static/**

    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 5  # Supabase 무료 플랜이면 5-10 권장
      minimum-idle: 2        # 최소 연결 수 줄이기
      idle-timeout: 300000   # 5분으로 줄이기
      max-lifetime: 900000   # 15분으로 줄이기
      leak-detection-threshold: 60000  # 연결 누수 감지 추가

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          autocommit: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # 비동기 처리 활성화
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      thread-name-prefix: async-task-

# JWT 설정
jwt:
  secret: duckhu-calendar-jwt-secret-key-must-be-at-least-32-characters-long-for-security
  expiration: 3600000 # 1시간 (밀리초)

# 서버 설정 - context-path 제거
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    duckhu.calendar: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 공공데이터 API 설정
public-data:
  api:
    holiday:
      base-url: "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService"
      service-key: "u9fo42I2R0K%2Fsc4Y81Kag3%2Fba%2BJXZQo%2FO213Nf45OSVJ7Rl8m2Lb9RQTjdVt4EUoBHlUE1NbxofSNHzYwjeIqg%3D%3D"
      timeout: 10000

# 외부 API 설정
external:
  api:
    retry:
      max-attempts: 3
      delay: 2000
    timeout: 15000

app:
  name: 이벤트 캘린더
  admin:
    email: nukabyte@gmail.com  # 관리자 이메일
  mail:
    from: noreply@duckhu-calendar.com  # 발신자 이메일
  dev:
    mode: true
